name: Build and Create Provenance
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact
        run:  zip build.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: build.zip

  generate-provenance:
    needs: build
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2

      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: artifact/

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          path: build.provenance

